version: '3.3'
services:

  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: pavelkor91/foodgram_project
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/uploads/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
      image: pavelkor91/foodgram_frontend
      volumes:
        - ../frontend/:/app/result_build/
      depends_on:
        - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/uploads/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

  volumes:
    postgres_data:
    static_value:
    media_value: